<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'System Check' => '',
    'Configuration DB' => '',
    'Install TrinitWeb DB' => '',
    'Configuration Auth DB' => '',
    'Configuration Character DB`s' => '',
    'Create administrator account' => '',
    'ReCaptcha' => '',
    'Mailer' => '',
    'TrinityWeb settings' => '',
    'End of installing' => '',
    'Recaptcha Configuration' => '',
    'Next step' => '',
    'Site Key (optional)' => '',
    'Secret (optional)' => '',
    'Creating administrator account' => '',
    'You\'re almost done. In the last step you have to fill out the form to create an admin account. With this account you can manage the whole website.' => '',
    'Repeat password' => '',
    'Email' => '',
    'Password' => '',
    'Username' => '',
    'Create Admin Account' => '',
    'Incorrect configuration' => '',
    'Requested step not allowed now!' => '',
    'Requested step not allowed now!' => '',
    'Application name' => '',
    'Tags' => '',
    'Description' => '',
    'Administrator Email' => '',
    'Robot Email' => '',
    'SMTP host' => '',
    'SMTP host for console app' => '',
    'SMTP port' => '',
    'SMTP username' => '',
    'SMTP password' => '',
    'SMTP encrypt' => '',
    'Databases' => '',
    'Host' => '',
    'Port' => '',
    'Congratulations! TrinityWeb installing complete!' => '',
    'Go to website' => '',
    'TrinityWeb settings' => '',
    'Name of database' => '',
    'Table prefix' => '',
    'Encrypt' => '',
    'TrinitWeb Installer' => '',
    'Database Configuration!' => '',
    'Below you have to enter your databases connections details. If you’re not sure about these, please contact your administrator.' => '',
    'DB Name' => '',
    'Name' => '',
    'Type realmname here...' => '',
    'Yes, database connection works!' => '',
    'Next' => '',
    '{dynamic_name} database configuration!' => '',
    'Below you have to enter your databases connections details. If you’re not sure about these, please contact your administrator.' => '',
    'Start import' => '',
    'Check again' => '',
    'Mailer settings' => '',
    'Congratulations! Everything is ok and ready to start over!' => '',
    'In the following overview, you can see, if all the requirements are ready.' => ''
];