<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Права доступа' => 'RBAC',
    'Модули' => 'Modules',
    'Магазин' => 'Store',
    'Упарвление категорией' => 'Manage category',
    'Добавить элемент' => 'Add element',
    'Просмотреть категорию' => 'View category',
    'Список категорий' => 'List of categories',
    '% скидки' => 'percent discount',
    'Дата окончания' => 'date end of discount',
    'Элемент магазина' => 'Item in store',
    'Начните вводить для поиска...' => 'Start typing for search...',
    'Оставить пустым если заполнено поле "Вещь"' => 'Leave blank if the "Item" field is filled',
    'Оставить пустым если заполнено поле "Наименование"' => 'Leave blank if the "Name" field is filled',
];
